#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCPIIO8uY8oWIihDv0tCAbX6toyG1RYkaLZyfGD1L+I07K4CnwAVBSU+81vw3Yv5sN9tj2Ccve9kzEeCNMld2mDP/Tt7edkx2MCToVfVx+njqwY/XbMY9bfdRKJLhIoLavuVNLnnkSIXdtlGr3JF71hPHzBDMEo64ofPCQ8hPsGxL1u3efb12jcWcRhudKtv7Qh6cVE47Zj4xImfi6VlLqwzcKZ5oCqR/z1hLLL+/pS3eM5Qsor5wmAqNfH4+z5eE+pOkFm7a0Nkygv9jwXIqtJzFGKYDe6ciBD04pEovdvY0FTyiv2vksQOVgjtu2faG2Iv1HOG0JktCIwJ49OEgjT teacher
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCU1B7+jwdy08QksJMs+swxlmIAShQnxtkoXbdLrE4rWktWEUGQHpwJWr/9+PSGcFUxgsvEHcAFzR59WKwB4uL1PCaGDeAxL+2h2W4jyt/sF20Q7J6haJe/7Ke5YK5EZpmcWtI5lQmxDoL32NFYRrp5pnjZ9lxGLvIyO8xMiYSrzqPqzW58P2Cf6vQXIE5bCq+KWRCSE3T9/ZTMrGoSCC5/v+AotFVwRbK8+tPS/8hGG4MfMkdXCk2vwCxcuzrei0CZl1lhsubBajjBsdVyckbDY0oOoWIVgP5Jmnaho1/bZaKUl7FEMU8ULOQfq+kiJLxX01ww7AUQTCrvR7CzTwrv aws-key
ssh_pwauth: false
disable_root: false
package_update: true   
packages:
- python3
write_files:
  - path: ~/app/server.py
    permissions: '0777'
    content: |
      from http.server import HTTPServer, SimpleHTTPRequestHandler
      from random import randint
      
      
      class MetricHandler(SimpleHTTPRequestHandler):
          def do_GET(self):
              if self.path == '/metrics':
                  self.send_response(200)
                  self.send_header("Content-type", "text/plain")
                  self.end_headers()
                  self.wfile.write(f"cpu {randint(0, 100)}".encode())
              else:
                  self.send_response(404)
                  self.send_header("Content-type", "text/plain")
                  self.end_headers()
                  self.wfile.write(b'Not Found')
      
      if __name__ == "__main__":
          port = 8080
          address = ("", port)
          httpd = HTTPServer(address, MetricHandler)
          print(f"Starting server at Port: {port}")
          httpd.serve_forever()
runcmd:
  - python3 ~/app/server.py
